Repository kazupon/vue-i18n, pull requests merged in 2019-08, with the labels that each got.

#675 Fix typo
  vuepress/guide/component.md
Labels: PR: reviewed-changes-requested

#685 support slots syntax for component interpolation
  examples/interpolation/places/index.html
  examples/interpolation/slots/index.html
  src/components/interpolation.js
  test/e2e/test/interpolation.js
  test/unit/interpolation.test.js
  vuepress/api/README.md
  vuepress/guide/interpolation.md
Labels: PR: unreviewed

#682 [docs] Update lazy-loading.md
  vuepress/guide/lazy-loading.md
Labels: PR: unreviewed, enhancement

#637 Add fallback formatting
  decls/i18n.js
  src/index.js
  src/mixin.js
  test/unit/basic.test.js
  types/index.d.ts
  vuepress/guide/fallback.md
Labels: PR: reviewed-approved

#688 Fix typo
  src/components/interpolation.js
Labels: PR: reviewed-approved
