Repository kazupon/vue-i18n, pull requests merged in 2020-10, with the labels that each got.

#1007 🔨 fix typo in example code
  vuepress/guide/fallback.md
Labels: PR: reviewed-approved

#1008 docs(tooling): adds vue-i18n-extract to the list of 3rd party tooling
  vuepress/guide/tooling.md
Labels: PR: reviewed-approved

#1011 minor release v8.22.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1012 Fix typo, espaceParameterHtml -> escapeParameterHtml in README. #1002
  vuepress/api/README.md
Labels: PR: reviewed-approved

#1020 escapeParameterHtml flag: Don't escape ampersand #1019
  src/util.js
  test/unit/escape_parameter_html.test.js
  vuepress/api/README.md
Labels: PR: reviewed-approved, Type: Breaking

#1021 patch release v8.22.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1023 docs: [RU] Translation update
  vuepress/ru/api/README.md
  vuepress/ru/guide/messages.md
  vuepress/ru/guide/tooling.md
Labels: PR: reviewed-approved
