Repository kazupon/vue-i18n, pull requests merged in 2020-03, with the labels that each got.

#791 Revise fallback.md
  vuepress/guide/fallback.md
Labels: PR: reviewed-approved

#787 Add a 'capitalize' default modifier for linked message
  gitbook/en/messages.md
  src/index.js
  test/unit/basic.test.js
  test/unit/fixture/index.js
Labels: PR: reviewed-approved

#798 fix: PR base branch
  CONTRIBUTING.md
Labels: PR: unreviewed, Type: Documentation

#797 Put dash at the end of character class in example i18n.js code.
  examples/hot/src/i18n.js
Labels: PR: reviewed-approved

#794 Support returning 'string' type for customized interpolation
  src/index.js
Labels: PR: reviewed-approved

#799 patch release v8.15.5
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved, release

#800 [release] wording in release template
  package.json
Labels: PR: reviewed-approved, Type: Maintenance

#816 Update fallback.md
  vuepress/guide/fallback.md
Labels: PR: reviewed-approved

#817 Bugfix : 'setLocaleMessage' / 'mergeLocaleMessage' doesn't work if 'warnHtmlInMessage' is set to 'error'
  src/index.js
  yarn.lock
Labels: PR: reviewed-approved

#818 patch release v8.15.6
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#819 Fixed bug when changing number format runtime
  src/index.js
  test/unit/number_component.test.js
Labels: PR: reviewed-approved

#820 patch release v8.15.7
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#822 post translation hooking feature
  decls/i18n.js
  src/index.js
  test/unit/post_translation.test.js
  types/index.d.ts
  vuepress/api/README.md
Labels: PR: unreviewed, Type: Feature

#823 minor release v8.16.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#824 Fix typo in documentation
  vuepress/guide/interpolation.md
  yarn.lock
Labels: PR: reviewed-approved
