Repository kazupon/vue-i18n, pull requests merged in 2020-07, with the labels that each got.

#942 Add vetur support for tags and attributes
  package.json
  vetur/attributes.json
  vetur/tags.json
Labels: PR: reviewed-approved

#944 minor release v8.19.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#928 :zap: improvement(interpolation): enable passage of local components to tag prop
  src/components/interpolation.js
  test/unit/interpolation.test.js
Labels: PR: reviewed-approved, Status: Need More Info, Type: Feature

#955 Revert "build(deps): [security] bump elliptic from 6.4.1 to 6.5.3 in /examples/sfc"
  examples/sfc/package-lock.json
Labels: PR: unreviewed

#959 i18n-n component local components passing
  src/components/number.js
  vuepress/api/README.md
Labels: PR: unreviewed, Type: Feature

#960 minor release v8.20.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#961 Update link to Formatter Interface
  vuepress/guide/formatting.md
Labels: PR: reviewed-approved, Type: Documentation
