Repository kazupon/vue-i18n, pull requests merged in 2020-04, with the labels that each got.

#832 fix in examples of "Custom pluralization"
  vuepress/guide/pluralization.md
  vuepress/zh/guide/pluralization.md
Labels: PR: reviewed-approved

#834 Add capitalize default modifier in doc
  docs/guide/messages.html
  vuepress/guide/messages.md
Labels: PR: reviewed-approved

#829 #138 Fallback Locale as array for cascading fallbacks
  gitbook/en/api.md
  gitbook/en/fallback.md
  src/index.js
  test/unit/fallback.test.js
Labels: PR: reviewed-approved, Type: Feature

#836 minor release v8.17.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#837 Fix typo
  README.md
Labels: PR: reviewed-approved, Type: Documentation

#840 fix: altnative endsWidth
  src/index.js
Labels: PR: unreviewed, Type: Bug

#841 patch release v8.17.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#843 Ensure IE11 compatibility using eslint
  .eslintrc.js
  package.json
  src/index.js
  yarn.lock
Labels: PR: reviewed-approved, Type: Maintenance

#844 Use plain object instead of Map, which is not supported in IE9/10
  src/index.js
Labels: PR: reviewed-approved, Type: Improvement

#845 patch release v8.17.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#846 add key to postTranslation
  decls/i18n.js
  src/index.js
  types/index.d.ts
Labels: PR: reviewed-approved, Type: Improvement

#847 docs: Update /api/README.md
  vuepress/api/README.md
Labels: PR: reviewed-approved, Type: Documentation

#848 patch release v8.17.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#857 fix: alternative array includes
  src/components/number.js
  src/index.js
  src/util.js
Labels: PR: unreviewed

#858 fix datetime and number format fallbacking
  src/index.js
  test/unit/datetime.test.js
  test/unit/number.test.js
Labels: PR: unreviewed, Type: Bug

#859 fix datetime format cache
  src/index.js
Labels: PR: unreviewed, Type: Bug

#860 patch release v8.17.4
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
