Repository kazupon/vue-i18n, pull requests merged in 2020-05, with the labels that each got.

#865 improvement(docs): extend Hot reloading section
  vuepress/guide/hot-reload.md
Labels: PR: reviewed-approved, Type: Documentation

#867 docs: [RU] Translation
  vuepress/.vuepress/config.js
  vuepress/ru/README.md
  vuepress/ru/api/README.md
  vuepress/ru/guide/component.md
  vuepress/ru/guide/datetime.md
  vuepress/ru/guide/directive.md
  vuepress/ru/guide/fallback.md
  vuepress/ru/guide/formatting.md
  vuepress/ru/guide/hot-reload.md
  vuepress/ru/guide/interpolation.md
  vuepress/ru/guide/lazy-loading.md
  vuepress/ru/guide/locale.md
  vuepress/ru/guide/messages.md
  vuepress/ru/guide/number.md
  vuepress/ru/guide/pluralization.md
  vuepress/ru/guide/sfc.md
  vuepress/ru/guide/tooling.md
  vuepress/ru/installation.md
  vuepress/ru/introduction.md
  vuepress/ru/legacy/README.md
  vuepress/ru/legacy/v5.md
  vuepress/ru/started.md
Labels: PR: reviewed-approved

#869 fix: not string method access error
  src/components/number.js
  src/directive.js
  src/index.js
  src/util.js
  test/unit/fallback.test.js
Labels: PR: unreviewed, Type: Bug

#870 patch release v8.17.5
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#871 update pluralization.md
  vuepress/guide/pluralization.md
Labels: PR: reviewed-approved, Type: Documentation

#872 docs: fixes
  vuepress/api/README.md
  vuepress/guide/directive.md
  vuepress/guide/fallback.md
  vuepress/guide/formatting.md
  vuepress/guide/hot-reload.md
  vuepress/guide/interpolation.md
  vuepress/guide/messages.md
  vuepress/guide/sfc.md
  vuepress/ru/api/README.md
  vuepress/zh/api/README.md
  vuepress/zh/guide/hot-reload.md
Labels: PR: unreviewed, Type: Documentation

#875 Add new 3rd party tool
  vuepress/guide/tooling.md
Labels: PR: reviewed-approved

#880 Don't delete _i18n in beforeDestroy
  src/mixin.js
  test/unit/component.test.js
  test/unit/issues.test.js
Labels: PR: reviewed-approved, Type: Bug

#881 patch release v8.17.6
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#882 fix v-t pluralisation when choice is 0
  src/directive.js
  test/unit/directive.test.js
Labels: PR: reviewed-approved, Type: Bug

#884 patch release v8.17.7
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#890 chore: set up linting for typescript definitions
  .flowconfig
  package.json
  types/.eslintrc.js
  types/test/component.ts
  types/test/index.ts
  yarn.lock
Labels: PR: reviewed-approved, Type: Improvement

#892 Add onComponentInstanceCreated constructor option
  decls/i18n.js
  src/index.js
  src/mixin.js
  types/index.d.ts
  vuepress/api/README.md
  vuepress/ru/api/README.md
Labels: PR: reviewed-approved, Type: Feature

#894 minor release v8.18.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#897 Update dependencies related to e2e testing and enable Unit testing on CI
  .circleci/config.yml
  config/karma.unit.ci.conf.js
  config/nightwatch.conf.js
  package.json
  test/e2e/runner.js
  yarn.lock
Labels: PR: reviewed-approved, Type: Maintenance

#896 Fix flow types and enable flow types testing on CI
  .circleci/config.yml
  decls/i18n.js
  src/index.js
  test/unit/issues.test.js
Labels: PR: unreviewed, Type: Bug

#899 patch release v8.18.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#900 Update most of dependencies related to testing
  .eslintrc.js
  examples/.eslintrc.js
  package.json
  test/.eslintrc.js
  test/helpers/wait-for-update.js
  test/unit/basic.test.js
  test/unit/component.test.js
  test/unit/custom_blocks.test.js
  test/unit/datetime.test.js
  test/unit/directive.test.js
  test/unit/interpolation.test.js
  test/unit/issues.test.js
  test/unit/message.test.js
  test/unit/number.test.js
  test/unit/number_component.test.js
  vuepress/guide/component.md
  vuepress/guide/fallback.md
  vuepress/ru/guide/component.md
  vuepress/ru/guide/fallback.md
  vuepress/zh/guide/component.md
  vuepress/zh/guide/fallback.md
  yarn.lock
Labels: PR: reviewed-approved, Type: Maintenance

#901 docs: (zh) inverse $d $n
  docs/zh/api/index.html
  vuepress/zh/api/README.md
Labels: PR: reviewed-approved, Type: Documentation
