Repository kazupon/vue-i18n, pull requests merged in 2020-06, with the labels that each got.

#902 docs: [RU] Translation update
  vuepress/ru/api/README.md
  vuepress/ru/guide/interpolation.md
  vuepress/ru/guide/number.md
  vuepress/ru/guide/tooling.md
  vuepress/ru/installation.md
Labels: PR: reviewed-approved, Type: Documentation

#910 Revert "build(deps): [security] bump websocket-extensions from 0.1.3 to 0.1.4"
  package-lock.json
  yarn.lock
Labels: PR: unreviewed

#917 fix: improve IVueI18n interface
  types/index.d.ts
Labels: PR: unreviewed, Type: Improvement

#918 patch release v8.18.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#920 Make link to API and Guide top level
  vuepress/.vuepress/config.js
Labels: PR: reviewed-approved

#921 Add lost pluralizationRules option to documentation
  decls/i18n.js
  vuepress/api/README.md
  vuepress/guide/pluralization.md
  vuepress/ru/api/README.md
  vuepress/ru/guide/pluralization.md
  vuepress/zh/api/README.md
  vuepress/zh/guide/pluralization.md
Labels: PR: reviewed-approved, Type: Documentation

#925 Added missing quote
  docs/guide/fallback.html
  gitbook/en/fallback.md
Labels: PR: unreviewed, Type: Documentation
