Repository kazupon/vue-i18n, pull requests merged in 2021-02, with the labels that each got.

#1114 Update tooling.md
  vuepress/zh/guide/tooling.md
Labels: PR: reviewed-approved

#1118 Fix wrong type for LocaleMatcher ('best-fit' to 'best fit').
  types/index.d.ts
Labels: PR: reviewed-approved, Type: Improvement

#1124 Add documentation for directive `choice` argument
  gitbook/en/api.md
Labels: PR: reviewed-approved, Type: Documentation

#1128 minor release v8.23.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
