Repository kazupon/vue-i18n, pull requests merged in 2021-07, with the labels that each got.

#1321 fix broken mergeLocaleMessage
  src/index.js
Labels: PR: reviewed-approved, Type: Bug

#1271 feat: Added formatter, values, path to MessageContext
  decls/i18n.js
  dist/vue-i18n.common.js
  dist/vue-i18n.esm.browser.js
  dist/vue-i18n.esm.browser.min.js
  dist/vue-i18n.esm.js
  dist/vue-i18n.js
  dist/vue-i18n.min.js
  src/index.js
  test/unit/message_function.test.js
  types/index.d.ts
  vuepress/guide/messages.md
  vuepress/pt/guide/messages.md
  vuepress/ru/guide/messages.md
  vuepress/zh/guide/messages.md
Labels: PR: reviewed-approved, Type: Feature

#1322 minor release v8.25.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1323 Added version notice for custom pluralizations
  vuepress/guide/pluralization.md
Labels: PR: reviewed-approved, Type: Documentation
