Repository kazupon/vue-i18n, pull requests merged in 2021-11, with the labels that each got.

#1410 patch release v8.26.6
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1411 fix: cannot work watchLocale on vue-i18n-bridge
  src/index.js
Labels: Type: Bug, PR: unreviewed

#1412 patch release v8.26.7
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1416 Update links to i18n Ally in tooling docs
  vuepress/guide/tooling.md
Labels: Type: Documentation, PR: reviewed-approved
