Repository kazupon/vue-i18n, pull requests merged in 2021-03, with the labels that each got.

#1139 experimental: add meta info for intlify tools
  src/mixin.js
Labels: PR: unreviewed, Type: Feature

#1143 minor release v8.24.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1145 Allowing paths to be null for lookups.
  src/path.js
  test/unit/path.test.js
Labels: PR: reviewed-approved, Type: Bug

#1146 patch release v8.24.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1151 fix: i18n reference to root causes memory leak (#1044)
  src/mixin.js
  test/unit/issues.test.js
Labels: PR: reviewed-approved, Type: Bug

#1152 $tc return type
  gitbook/en/api.md
Labels: PR: reviewed-approved, Type: Documentation

#1153 patch release v8.24.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
