Repository kazupon/vue-i18n, pull requests merged in 2021-04, with the labels that each got.

#1175 [perf] Use Set so lookup of _dataListeners can be O(1)
  src/index.js
  src/util.js
Labels: PR: unreviewed, Type: Bug, Type: Performance

#1176 patch release v8.24.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1181 docs: (ru) fix links
  vuepress/ru/installation.md
  vuepress/ru/started.md
Labels: PR: reviewed-approved

#1192 Revert "fix: i18n reference to root causes memory leak (#1044)"
  src/mixin.js
  test/unit/issues.test.js
Labels: PR: unreviewed, Type: Bug

#1193 patch release v8.24.4
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
