Repository kazupon/vue-i18n, pull requests merged in 2021-06, with the labels that each got.

#1258 Grammar fix for Installing vue-i18n-loader
  vuepress/guide/sfc.md
Labels: PR: reviewed-approved

#1267 Documentation - Update @kazupon/vue-i18n-loader to @intlify/vue-i18n-loader
  docs/guide/sfc.html
  vuepress/guide/sfc.md
Labels: PR: reviewed-approved

#1269 [fix] lazy-loading.md
  vuepress/guide/lazy-loading.md
Labels: PR: reviewed-approved

#1270 Revert "[fix] lazy-loading.md"
  vuepress/guide/lazy-loading.md
Labels: PR: unreviewed

#1273 docs(api:zh): update the Chinese docs of "API"
  vuepress/zh/api/README.md
Labels: PR: reviewed-approved, Type: Documentation

#1278 fix: Ensure that the order at desroy is the same as before change to `Set` from `Array`
  src/index.js
  src/util.js
Labels: PR: unreviewed, Type: Bug

#1280 patch release v8.24.5
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
