Repository kazupon/vue-i18n, pull requests merged in 2021-09, with the labels that each got.

#1381 fix: linked messages containing slash symbol
  src/index.js
  test/unit/issues.test.js
Labels: Type: Bug, PR: unreviewed, PR: reviewed-approved

#1382 patch release v8.25.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1385 feat: support for vue-i18n-bridge
  decls/i18n.js
  package.json
  src/index.js
  src/install.js
  src/mixin.js
  test/unit/mixin.test.js
  types/index.d.ts
  yarn.lock
Labels: Type: Feature, PR: unreviewed

#1388 feat: add sync property
  src/index.js
  types/index.d.ts
Labels: Type: Improvement, PR: unreviewed

#1389 patch release v8.26.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1390 improvement: add flags for vue-i18n-bridge
  decls/i18n.js
  src/index.js
Labels: Type: Improvement, PR: unreviewed

#1391 patch release v8.26.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1392 improvement: vue-i18n-loader bridge mode
  src/mixin.js
  test/unit/custom_blocks.test.js
Labels: Type: Improvement, PR: merged

#1393 patch release v8.26.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
