Repository kazupon/vue-i18n, pull requests merged in 2021-01, with the labels that each got.

#1096 @types: Fixed too narrow option types in n() and d() methods
  types/index.d.ts
Labels: PR: reviewed-approved

#1097 patch release v8.22.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1102 [pt-BR] Documentation write in Portuguese
  vuepress/.vuepress/config.js
  vuepress/pt/README.md
  vuepress/pt/api/README.md
  vuepress/pt/guide/component.md
  vuepress/pt/guide/datetime.md
  vuepress/pt/guide/directive.md
  vuepress/pt/guide/fallback.md
  vuepress/pt/guide/formatting.md
  vuepress/pt/guide/hot-reload.md
  vuepress/pt/guide/interpolation.md
  vuepress/pt/guide/lazy-loading.md
  vuepress/pt/guide/locale.md
  vuepress/pt/guide/messages.md
  vuepress/pt/guide/number.md
  vuepress/pt/guide/pluralization.md
  vuepress/pt/guide/sfc.md
  vuepress/pt/guide/tooling.md
  vuepress/pt/installation.md
  vuepress/pt/introduction.md
  vuepress/pt/legacy/README.md
  vuepress/pt/legacy/v5.md
  vuepress/pt/started.md
Labels: PR: reviewed-approved

#1101 Improve performance of mergeLocaleMessage (#1099)
  src/index.js
Labels: PR: reviewed-approved, Type: Performance

#1105 patch release v8.22.4
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
