Repository kazupon/vue-i18n, pull requests merged in 2022-10, with the labels that each got.

#1568 changed useGrouping option to right type in the documentation
  gitbook/en/api.md
  vuepress/api/README.md
  vuepress/zh/api/README.md
Labels: PR: reviewed-approved

#1569 fix(datetime): $d supports key format object (#1502)
  examples/datetime/index.html
  src/index.js
  src/util.js
  test/e2e/test/datetime.js
Labels: Type: Feature, PR: reviewed-approved

#1570 minor release v8.28.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1572 fix(datetime): support all key format object (kazupon#1571)
  src/util.js
Labels: Type: Improvement, PR: unreviewed, PR: reviewed-approved

#1573 patch release v8.28.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#1575 fix(datetime): fixing calender typo
  src/util.js
Labels: PR: reviewed-approved

#1576 patch release v8.28.2
  CHANGELOG.md
  package.json
Labels: PR: unreviewed
